### ISSUE TITLE
No content to map due to end-of-input

### ISSUE THREAD

**Issue by mehhrad** [charlieAndroidDev/Instagram4Android#11] opened 2017-09-11 11:59 UTC
i get this exception after some api calls ...

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input W/System.err: at [Source: ; line: 1, column: 0] W/System.err: at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838) W/System.err: at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783) W/System.err: at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842) W/System.err: at dev.niekirk.com.instagram4android.requests.InstagramRequest.parseJson(InstagramRequest.java:112) W/System.err: at dev.niekirk.com.instagram4android.requests.InstagramRequest.parseJson(InstagramRequest.java:98) W/System.err: at dev.niekirk.com.instagram4android.requests.InstagramGetUserFollowersRequest.parseResult(InstagramGetUserFollowersRequest.java:35) W/System.err: at dev.niekirk.com.instagram4android.requests.InstagramGetUserFollowersRequest.parseResult(InstagramGetUserFollowersRequest.java:14) W/System.err: at dev.niekirk.com.instagram4android.requests.InstagramGetRequest.execute(InstagramGetRequest.java:42) W/System.err: at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:195)`

what does it mean?

how to avoid it ?

and how to react ?(logging again?)

**Comment by charlieAndroidDev** [comment] 2017-09-12 15:44
I must say I've never seen this before, can you give some steps to reproduce this?

**Comment by mehhrad** [comment] 2017-09-12 17:44
```
@Test
    public void getUserFollowers() throws InterruptedException {
        Observable<Instagram4Android> source = InstaHelper.getInstaObservableInfinteRetry("user__", "pass");
        source.map(insta ->{
            InstagramUser userrr = insta.sendRequest(new InstagramSearchUsernameRequest("rezagolzar")).getUser();//this user has 5 million follower
            String nextMaxId = "";
            List<InstagramUserSummary> totalList= new ArrayList<>();

            do {
                try {
                    InstagramGetUserFollowersResult result = insta.sendRequest(new InstagramGetUserFollowersRequest(userrr.getPk(), nextMaxId));
                    nextMaxId = result.getNext_max_id();
                    totalList.addAll(result.getUsers());
                    Log.e(TAG, "etc: total list size is:"+ totalList.size());
                    Log.d(TAG, "etc: nextMaxId is:"+ nextMaxId );
                    for (InstagramUserSummary item : result.getUsers()) {
                        Log.i(TAG, "etc: item : + " + item.getUsername());
                    }
                } catch (IOException e) {
                    Log.e(TAG, "etc: RIDI",e);
                    if (e.toString().toLowerCase().contains("No content to map due to end-of-input".toLowerCase())){
                        insta = InstaHelper.getInsta4anSyncOrThrow("mehradtest","6849788mehrad");
                        Log.e(TAG, "etc: SIGN ing IN AGAIN");
                    }
                }

            }while (nextMaxId != null);
            return "";
        }).subscribe();

        Thread.sleep(1000*60*10);
    }
```

LogCat:
```
...
E/InstaHelper: etc: total list size is:14283
E/InstaHelper: etc: total list size is:14478
E/InstaHelper: etc: RIDI
               com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
                at [Source: ; line: 1, column: 0]
                   at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
                   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
                   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
                   at dev.niekirk.com.instagram4android.requests.InstagramRequest.parseJson(InstagramRequest.java:112)
                   at dev.niekirk.com.instagram4android.requests.InstagramRequest.parseJson(InstagramRequest.java:98)
                   at dev.niekirk.com.instagram4android.requests.InstagramGetUserFollowersRequest.parseResult(InstagramGetUserFollowersRequest.java:35)
                   at dev.niekirk.com.instagram4android.requests.InstagramGetUserFollowersRequest.parseResult(InstagramGetUserFollowersRequest.java:14)
                   at dev.niekirk.com.instagram4android.requests.InstagramGetRequest.execute(InstagramGetRequest.java:42)
                   at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:195)
                   at semycolon.mehrad.instasubmarine.InstaLikeFeed.lambda$getUserFollowers$6$InstaLikeFeed(InstaLikeFeed.java:211)
                   at semycolon.mehrad.instasubmarine.InstaLikeFeed$$Lambda$5.apply(Unknown Source)
                   at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
                   at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:262)
                   at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:559)
                   at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onNext(ObservableRetryPredicate.java:69)
                   at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
                   at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
                   at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
                   at io.reactivex.Observable.subscribe(Observable.java:10903)
                   at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
                   at io.reactivex.Observable.subscribe(Observable.java:10903)
                   at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.subscribeNext(ObservableRetryPredicate.java:111)
                   at io.reactivex.internal.operators.observable.ObservableRetryPredicate.subscribeActual(ObservableRetryPredicate.java:41)
                   at io.reactivex.Observable.subscribe(Observable.java:10903)
                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                   at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                   at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                   at java.lang.Thread.run(Thread.java:818)
E/InstaHelper: etc: SINGing IN AGAIN
E/InstaHelper: etc: total list size is:14677
E/InstaHelper: etc: total list size is:14876
E/InstaHelper: etc: total list size is:15072
...
```

**Comment by charlieAndroidDev** [comment] 2017-09-13 01:53
If logging in again works, do that.  But going through all user ids with no pause is spammy behaviour and IG is probably blocking it.  Try to have a pause in between each InstagramGetUserFollowersRequest, if you think about it a user cannot even scroll fast enough to fire network calls as quickly as you currently do them.

**Comment by mehhrad** [comment] 2017-09-13 10:51
you're right i got the exact same result with pausing. i thought that maybe instagram change the token or sth after certain calls.

**Comment by charlieAndroidDev** [comment] 2017-09-21 14:35
Closing for now as this seems to be and issue in usage of the library rather than the library itself.

**Closed by charlieAndroidDev** 2017-09-21 14:35 UTC
